export const GET_LATEST_RECIPE_PENDING = 'GET_LATEST_RECIPE_PENDING';
export const GET_LATEST_RECIPE_SUCCESS = 'GET_LATEST_RECIPE_SUCCESS';
export const GET_LATEST_RECIPE_FAILED = 'GET_LATEST_RECIPE_FAILED';

export const GET_LIST_RECIPE_PENDING = 'GET_LIST_RECIPE_PENDING';
export const GET_LIST_RECIPE_SUCCESS = 'GET_LIST_RECIPE_SUCCESS';
export const GET_LIST_RECIPE_FAILED = 'GET_LIST_RECIPE_FAILED';

export const GET_DETAIL_USER_PENDING = 'GET_DETAIL_USER_PENDING';
export const GET_DETAIL_USER_SUCCESS = 'GET_DETAIL_USER_SUCCESS';
export const GET_DETAIL_USER_FAILED = 'GET_DETAIL_USER_FAILED';

export const GET_DETAIL_RECIPE_PENDING = 'GET_DETAIL_RECIPE_PENDING';
export const GET_DETAIL_RECIPE_SUCCESS = 'GET_DETAIL_RECIPE_SUCCESS';
export const GET_DETAIL_RECIPE_FAILED = 'GET_DETAIL_RECIPE_FAILED';

export const GET_RECIPE_COMMENTS_PENDING = 'GET_RECIPE_COMMENTS_PENDING';
export const GET_RECIPE_COMMENTS_SUCCESS = 'GET_RECIPE_COMMENTS_SUCCESS';
export const GET_RECIPE_COMMENTS_FAILED = 'GET_RECIPE_COMMENTS_FAILED';

export const GET_USER_RECIPES_PENDING = 'GET_USER_RECIPES_PENDING';
export const GET_USER_RECIPES_SUCCESS = 'GET_USER_RECIPES_SUCCESS';
export const GET_USER_RECIPES_FAILED = 'GET_USER_RECIPES_FAILED';

export const GET_USER_LIKED_RECIPE_PENDING = 'GET_USER_LIKED_RECIPE_PENDING';
export const GET_USER_LIKED_RECIPE_SUCCESS = 'GET_USER_LIKED_RECIPE_SUCCESS';
export const GET_USER_LIKED_RECIPE_FAILED = 'GET_USER_LIKED_RECIPE_FAILED';

export const GET_USER_SAVED_RECIPE_PENDING = 'GET_USER_SAVED_RECIPE_PENDING';
export const GET_USER_SAVED_RECIPE_SUCCESS = 'GET_USER_SAVED_RECIPE_SUCCESS';
export const GET_USER_SAVED_RECIPE_FAILED = 'GET_USER_SAVED_RECIPE_FAILED';
